version: '3'
services:
  mysql:
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: juego
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
  php-apache:
    build:
      context: ./html
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    networks:
      - my-network
volumes:
  mysql-data:
networks:
  my-network: